server:
  port: 8081
spring:
  application:
    name: user-consumer  #应用名称，会在Eureka中显示
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  client:
    service-url:  # EurekaServer地址
      defaultZone: http://127.0.0.1:8083/eureka
    registry-fetch-interval-seconds: 5 #
  instance:
    prefer-ip-address: true   # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1  # 指定自己的ip信息，不指定的话会自己寻找

#    lease-expiration-duration-in-seconds: 1 #服务失效时间，默认值90秒
#    lease-renewal-interval-in-seconds: 1 #服务续约(renew)的间隔，默认为30秒
user-service:
  ribbon:
    ConnectTimeout: 250 # Ribbon的连接超时时间
    ReadTimeout: 1000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数
logging:
  level:
    root: info
    org:
    springframework:
      retry: debug
